const AGREGAR_ACTIVIDAD_TURISTICA = 'AGREGAR_ACTIVIDAD_TURISTICA';
const ELIMINAR_ACTIVIDAD_TURISTICA = 'ELIMINAR_ACTIVIDAD_TURISTICA';
const FILTRAR_PAISES = 'FILTRAR_PAISES';
const ORDENAR_PAISES= 'ORDENAR_PAISES';

module.exports = {
    AGREGAR_ACTIVIDAD_TURISTICA,
    ELIMINAR_ACTIVIDAD_TURISTICA,
    FILTRAR_PAISES,
    ORDENAR_PAISES
}